Fix: 웹 스코프 - 스코프 확인
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'logDemoController' defined in file
...
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.

1. 에러 원인
LogDemoController 에서 MyLogger 를 주입하는데
MyLogger 의 scope 는 request 이므로
서버가 기동시에는 아직 스프링 컨테이너가 해당 빈을 가지고 있지 않다.
따라서 에러가 뜨는것이 맞다.