Fix: @ComponentScan 중복 처리 (동일 이름 충돌)
동일한 이름의 comopnent 를 등록하면 오류 발생

BeanDefinitionStoreException: Failed to parse configuration.. bean name 'service' for bean class [...] conflicts with existing, non-compatible bean definition of same name and class [.....]